baseURL       = "https://studio-mizutama.net/"
#languageCode  = "en-us"
DefaultContentLanguage = "en"
#DefaultContentLanguageInSubdir = true
title         = "Studio Mizutama Official Site"
theme         = "roxo"
summarylength = 25
publishDir    = "docs"
canonifyurls  = true

[Languages]
  [Languages.en]
    weight = 1
  [Languages.ja]
    weight = 2

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Works"
    url     = "works"
    weight  = 3
  [[menu.nav]]
    name    = "News"
    url     = "news"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/mizutamalogo.svg"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Studio Mizutama produces animation and other video works, applications for video production, and web media."
  author = "Studio Mizutama Association Inc."
  # Google Analitycs
  # googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  # formspreeFormUrl  = "https://formspree.io/f/minorin@studio-mizutama.net"
  customCSS = ["/css/custom.css"]
  og_image = "/images/card.png"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.png"
    heading               = "Online Animation Studio"
#    tagline               = "WE WORK HARD, WE PLAY HARD"
    primary_button        = "See Our Works"
    primary_button_url    = "works"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.about]
    enable    = true
    title     = "ABOUT US"
    subtitle  = "Studio Mizutama produces animation and other video works, applications for video production, and web media. Our goal is to contribute to the promotion of the digital media production field by publishing the results and the technical knowledge gained through the production. We publish them on GitHub and Qiita."

  [params.portfolio]
    enable    = true
    title     = "OUR RECENT WORKS"
    subtitle  = "We are making original animes and apps for anime creators."

  [params.call_to_action]
    enable              = true
    #background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button        = "See Our Works"
    primary_button_url    = "works"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "1-24-6 Shakujii-machi<br>Nerima-ku, Tokyo 177-0041"
      #phone   = "409-896-1444"
      email   = "info@studio-mizutama.net"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Works"
          url  = "works"
        [[params.footer.sitemap.link]]
          name = "News"
          url  = "news"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "GitHub"
          name_s = "github"
          url  = "https://github.com/studio-mizutama"
        [[params.footer.social.link]]
          name = "Qiita"
          name_s = "search"
          url  = "https://qiita.com/organizations/studio-mizutama"
        [[params.footer.social.link]]
          name = "Twitter"
          name_s = "twitter"
          url  = "https://twitter.com/Studio_Mizutama"
        [[params.footer.social.link]]
          name = "YouTube"
          name_s = "youtube"
          url  = "https://www.youtube.com/channel/UCeeMcZ9w-domt4oGO2KBjBw"
      # Footer Service
      [params.footer.service]
        title       = "Our Activities"
        description = "Animation & Motion Graphics<br>Application Development<br>Web Development "

 [markup.goldmark.renderer]
  unsafe = true
